name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.5
        args: install
    - name: Lint with black
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.5
        args: run black . --check -l 79
    - name: Test with pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: 1.0.5
        args: run pytest tests/
